config/routes.rb
Rails.application.routes.draw do

  get 'autocomplete/user_json'

  get 'map/show'

  resources :users
  resources :word_tokens, only: [:new, :create, :destroy]
  resources :handshakes, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :user_word_tokens, only: [:create]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  

  root 'welcome#home'

end

app/models/user.rb
class User < ActiveRecord::Base

	# Word Token - User Relations
	has_many :active_connections, class_name: "UserWordToken",
							foreign_key: "giver_id",
							dependent: :destroy

	has_many :passive_connections, class_name: "UserWordToken",
							   foreign_key: "receiver_id",
							   dependent: :destroy


	# Handshake - User - Relations
	#Handshake Relationship
	has_many :handshakes
	has_many :hand_connections, :through => :handshakes
	has_many :inverse_handshakes, :class_name => "Handshake", :foreign_key => "connection_id"
	has_many :inverse_hand_connections, :through => :inverse_handshakes, :source => :user

	# Request - Relations
	has_many :requests
	has_many :req_connections, :through => :requests
	has_many :inverse_requests, :class_name => "Request", :foreign_key => "connection_id"
	has_many :inverse_req_connections, :through => :inverse_requests, :source => :user

	# Credibility - Relations
	has_many :credibility_systems


	# Validations 
	validates :name,  presence: true, length: { maximum: 30 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                    format: { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }

	has_secure_password



	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

	

	# give another user a token
	 def give_token(other_user, word_token)
		active_connections.create(receiver_id: other_user.id, word_token_id: word_token.id)
	 end

	 # take token back 
	def ungive_token(other_user)
	 	active_connections.find_by(receiver_id: other_user.id).destroy
	end

	def given?(other_user, word_token)
		#iterate over given tokens
		#determine if token exist
		#return true
		active_connections.select { |l| 
			l.receiver == other_user && l.word_token.label == word_token.label 
		 }.size > 0
	end


	 def request_handshake(other_user)
	 	requests.create(connection_id: other_user.id)
	 end

	 def cancel_request(other_user)
	 	inverse_requests.find_by(user_id: other_user.id).destroy
     end

     def accept_handshake(other_user)
     	handshakes.create(connection_id: other_user.id)
     	cancel_request other_user
     end

	 def shook_hands?(other_user)
	 	handshakes.find_by(connection_id: other_user.id) || inverse_handshakes.find_by(user_id: other_user.id)
	 end

	 def made_requests?(other_user)
	 	requests.find_by(connection_id: other_user.id) || inverse_requests.find_by(user_id: other_user.id)
	 end


	 # Credibility

	 def give_credibility(other_user)
	 	current_user_cb = CredibilitySystem.find_by(user_id: self.id).points
	 	weight = (current_user_cb * 0.10).to_i
	 	other_user_sys = CredibilitySystem.find_by(user_id: other_user.id)
	 	other_user_points = CredibilitySystem.find_by(user_id: other_user.id).points
	 	other_user_sys.update(points: other_user_points + weight)
	 end
	
	# Set up accessible (or protected) attributes for your model
    def user_params
	 params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only:   [:edit, :update]
  before_action :update_last_seen


  def index
    # @search = User.search do 
    #   fulltext params[:search]
    # end
    @users = User.last(30)
  end

  def show
    @user = User.find(params[:id])
    @credibility = CredibilitySystem.find_by(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def udpdate
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit

  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.credibility_systems.create(points: "100")
      log_in @user
      flash[:success] = "Welcome to WordToken!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def create_via_oauth
    data = request.env['omniauth.auth']
    uid = data.uid
    @user = User.find_by oauth_id: uid
    if (@user) 
      log_in(@user)
    else 
      fake_email = (0...50).map { ('a'..'z').to_a[rand(26)] }.join + "@nulnulnulnul.com"
      fake_password  = (0...50).map { ('a'..'z').to_a[rand(26)] }.join + "@nulnulnulnul.com"
      name = data.info.name.split.first
      @user = User.new(oauth_id: uid, name: name, email: fake_email, password: fake_password)
      @user.save
      @user.credibility_systems.create(points: "100")
      log_in @user
      flash[:success] = "Welcome to WordToken!"
    end
      redirect_to @user
  end

  def destroy
    user = User.find(params[:id])
    unless current_user?(user) 
      user.destroy 
      flash[:success] = "User deleted."
    end
    redirect_to users_url
  end

  # def notable_givers
  #   @title = "Notable Givers"
  #   @user = User.find(params[:id])
  #   @users = @user
  # end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    unless user_signed_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_handshake_form.html.erb
_handshake_form.html.erb

app/views/users/_request_form.html.erb
<% unless current_user? @user  %>
    <div class="button give_token">Give Token</div>
	<% if current_user.shook_hands? @user %>
	 <div class="button shake">Connected</div>
	<% elsif current_user.made_requests? @user %>
		<div class="button shake">Shake Pending..</div>
	<% else %>
		<%= form_for(current_user.requests.build(connection_id: @user.id)) do |f| %>
		<div><%= hidden_field_tag :connection_id, value = @user.id %></div>
		<%= f.submit "Shake Hands", class: "button shake" %>
		<% end %>

	<% end %>
<% end %>

app/views/users/_transfer_token_form.html.erb
<%= form_tag(user_word_tokens_path) do %>
 	<div class="instruction">Choose any amount of Word Tokens that you want to give..</div>
	<div class="tags">
        <% WordToken.all.each do |token| %>
        <label>
        <% next if current_user.given? @user, token %>
	        <%= check_box_tag("Tokens[#{token.label}]", token.id)  %>
	        <%= hidden_field_tag :connection_id, value = @user.id %>
	        <%= token.label %>
	    </label>
         <% end %> 
 	</div>
	<div class="instruction">Once you have one or more tokens selected click Vouch</div> 
 	<div> <%= submit_tag("Vouch", class: "btn_give") %> </div>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% content_for :header_style do %>
  <link rel="stylesheet" type="text/css" href="/user_index.css">
<% end %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">
<div class="cont main">
	<h3>Recently Joined Users</h3>
	<div class="users animated fadeInDown">
		<% @users.each do |x| %>
			<%= link_to(x, class: 'no_underline') do %>
				<div class="user">
					<div class="img"><%= gravatar_for(x, 50) %></div>
					<div class="name"> <%= x.name %></div>
				</div>
			<% end %>
		<% end %>
		
	</div>
</div>

app/views/users/new.html.erb
<% content_for :header_style do %>
  <link rel="stylesheet" type="text/css" href="/sign_up_in.css">
<% end %>


<%= form_for(@user) do |f| %>

  <div class="cont main">
    <div class="stuff">
      <div class="btn">
        <div class="title signup open">Sign Up</div>
        <div class="form">
          <form>
            <table>
              <tr>
                <td>
                  <%= f.label :name %>
                </td>

                <td> 
                  <%= f.text_field :name %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= f.label :email %><br />
                
                </td>

                <td>
                  <%= f.email_field :email, autofocus: true %>
                </td>
                
              </tr>
              <tr>
                <td>
                  <%= f.label :password %>
                </td>
                <td>
                  <%= f.password_field :password %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= f.label :password_confirmation %><br />
                </td>
                <td>
                  <%= f.password_field :password_confirmation, autocomplete: "off" %>
                </td>
              </tr>
            </table>
            <%= f.submit "Sign up" %>
          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for :header_style do %>
  <link rel="stylesheet" type="text/css" href="/user_profile.css">
<% end %>

<div class="cont main">
  <div class="profile_bg">
    <!-- Handicon image -->
    <% if current_user == @user  %>
      <%= render 'handshake_icon' %>
    <% end %>


    <div class="profile_pic"><%= gravatar_for @user, 190 %></div>
  </div>
  <div class="about">
    <div class="stats">
      <div class="credibility">
        <div class="num"><%= @credibility.points %></div>
        <div class="title">Credibility</div>
      </div>
      <div class="handshakes">
      <% handshakes = @user.handshakes.count + @user.inverse_handshakes.count %>
        <div class="num"><%= handshakes %></div>
        <div class="title"><%= handshakes == 1 ? "Handshake": "Handshakes" %></div>
      </div>
      <div class="divider"></div>
      <div class="all_tokens">
        <div class="num"><%= @user.tokens_received.count%></div>
        <div class="title">Tokens</div>
      </div>
     
        <div class="last_active">
          <% time = (Time.now.min - @user.last_seen.min).abs %>
          <% if (time == 0) %>
            <div class="num">Now</div>
          <% else %>
            <div class="num"><%= Time.now.min - @user.last_seen.min %>m</div>
          <% end %>
          <div class="title">Last Seen</div>
        </div>

    </div>
    <div class="name_sect">
      <div class="name">
        <div class="line"></div>
        <div class="text"><%= @user.name %></div>
      </div>
    </div>



    <div class="two_columns">
      <div class="left">
      <% token_data = @user.passive_connections.group_by { |e| e.word_token.label }.sort_by {|k,v| v.size}.reverse %>

        <h3>Tokens</h3>
        <div class="no_token_msg hide">Welcome, Your WordTokens will show up here. Get your friends to connect with you.</div>
        <div class="tokens">
        <% token_data.each do |e| %> 
          <div class="token">
            <div class="tag">
              <div class="word"><%= e.first %></div>
              <span class="times">x</span>
              <span class="num"><%= e[1].count %></span>
            </div>

            <div class="people">
           <% e[1].each do |e| %>
              <div class="person"><%= link_to gravatar_for(e.giver, 50), e.giver %></div>
          <% end %>
            </div>
          </div>
        <% end %>
        </div>






        <div class="show_more">
          Show More
        </div>

        <div class="handshakers">
          <h3>HandShakes</h3>
          <% total_handshakes_users = @user.handshakes.map {|x| x.connection } + @user.inverse_handshakes.map {|x| x.user } %>
          <% total_handshakes_users.each do |x| %>
            <div class="person"><%= link_to( ( gravatar_for(x,35) ) + x.name, x) %></div>
          <% end %>
        </div>


      </div>
      <div class="right">


        <div class="buttons">
          <%= render 'request_form' %>
        </div>

        <div class="notable">
          <div class="title">Notable Givers</div>
          <% notable_users = @user.passive_connections.group_by(&:giver).keys.sort_by { |x| x.credibility_systems.first.points }.reverse[0..9] %>
          <% notable_users.each do |user|%>
            <%= link_to(user) do %>
              <div class="person">
                <div class="img"><%= gravatar_for(user,40) %></div>
                <div class="info"> 
                  <span class="name"><%= user.name %></span>
                  <span class="credibility"><%= user.credibility_systems.first.points %></span>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="to_top">
  <div class="line"></div>
  <div class="box">Go to Top</div>
</div>


<div class="token_box">
  <div class="dialog">
    <div class="title">
      Give <span><%= @user.name %></span> A Token
    </div>
    <div class="box">
      <%= render 'transfer_token_form' %>
    </div>
  </div>
</div>

<div class="notification_box">
  <div class="dialog">
<% current_user.inverse_requests.each do |req| %>

  <% @req = req %>
    <div class="user"> 
      <div class="img"><%= link_to (gravatar_for @req.user, 35 ), @req.user %></div>
      <div class="name"><%= link_to req.user.name, @req.user %></div>
      
      <div class="btns">

        <div class="accept"><%= render 'accept_form' %></div>
        <div class="decline"><%= render 'decline_form' %></div>

      </div>
    </div>
<% end %>
  </div>
</div>

<script src="/user_profile.js"></script>

app/views/users/udpdate.html.erb
<h1>Users#udpdate</h1>
<p>Find me in app/views/users/udpdate.html.erb</p>