config/routes.rb
Rails.application.routes.draw do

  get 'autocomplete/user_json'

  get 'map/show'

  resources :users
  resources :word_tokens, only: [:new, :create, :destroy]
  resources :handshakes, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :user_word_tokens, only: [:create]
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  

  root 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :update_last_seen
	
  def home
  	@user = current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<% content_for :header_style do %>
  <link rel="stylesheet" type="text/css" href="main.css">
<% end %>


<div class="cont main">
  <div class="hero">
    <div class="text">
      <div class="rotated">
        WordToken is a Network for Credibility. The simple solution that provides Trust & Legitimacy for the internet.
      </div>
    </div>



    <div class="search">
      <input id= 'search_input_box' type="text" placeholder='Find Someone' />
<!--     <%= form_tag users_path, :method => :get do %>

      <%= text_field_tag :search, params[:search], id: 'search_input_box' %>
      
    <% end %> -->
    <div class="suggestions hide">
      <!-- <div class="user">
        <a href="#">
          <div class="img"></div>
          <div class="name">Test</div>
        </a>
      </div> -->
      <div class="no_user hide">No Users found</div>
    </div>
    </div>

    

    <div class="action">
      <div class="circle">
        <% if user_signed_in? %>
        <%= link_to "Let's Trust", current_user %>
      <% else %>
        <%= link_to "Let's Trust", signup_path %>
      <% end %>
      </div>
    </div>
  </div>

    <%= link_to(user_signed_in? ? users_path : login_path, class: 'no_underline recent_parent') do %>
      <div class="view_recent">View Recent Users</div>
    <% end %>

  <div class="features">
    <div class="feature">
      <div class="img">
        <img src="http://cdn.flaticon.com/svg/32/32441.svg" />
      </div>
      <div class="text">
        <div class="title">Develop a Reputable Network</div>
  <!--    <div class="desc">Every user has crediblity, some more than others. Higher reputation of a user indicates that they are well known for their qualities and connected. Crediblity per token rises if Person vouching has high crediblity. Crediblity is a good indicator of person's integerity and skills.</div> -->

        <div class="desc">Every user has credibility modelled through a fixed and weighted point system. Our 'trust algorithm' allows users to accumulate credibility points by receiving vouches for their credentials and establishing associations with reputable members of the WordToken network. </div>
      </div>
    </div>
    <div class="feature">
      <div class="img">
        <img src="http://cdn.flaticon.com/svg/46/46749.svg" />
      </div>
      <div class="text">
        <div class="title">Vouch by Awarding WordTokens</div>
        <div class="desc">WordToken's are a social way to pass information about a person to others. Award others WordTokens that demonstrate their skill or quality. Each WordToken has value based on 10% of a users credibility points. Give them sparingly as too many may inversely affect your own score. </div>
      </div>
    </div>
    <div class="feature">
      <div class="img">
        <img src="http://cdn.flaticon.com/svg/46/46778.svg" />
      </div>
      <div class="text">
        <div class="title">Connect with People and Organizations</div>
       

        <div class="desc">
       Handshakes represent connections between users and is a great indicator of who a user supports. Handshakes have the greatest weight on a users credibility so select your friends wisely.
        </div>
      </div>
    </div>
    <div class="feature">
      <div class="img">
        <img src="http://cdn.flaticon.com/svg/71/71424.svg" />
      </div>
      <div class="text">
        <div class="title">Find the Best</div>
        <div class="desc">Members compete to reach the peak of the leaderboards and become the most repuatable user in their field. WordToken makes it easy to filter users by a host of credibility stats helping you to find the best in the network for a particular skill or by industry.</div> 
      </div>
    </div>
  </div>
</div>
<div class="to_top">
  <div class="line"></div>
  <div class="box">Go to Top</div>
  <div id="contact">Contact us at admin@wordtoken.io</div>
</div>

<script src="/main.js"></script>